import { useNavigate } from "react-router-dom";
import { BarChart3, Clock3, Search, BookOpenCheck, ChevronRight, LockKeyhole, Users, Settings2, ShieldCheck, CalendarDays } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { currentProfile } from "@/data/mock";
import { FadeIn, Stagger, motion, fadeUp } from "@/components/MotionPrimitives";

export default function MePage() { const nav = useNavigate(); return <div className="min-h-full bg-[color:var(--background)] pb-5">
  <header className="px-5 pb-5 pt-4"><FadeIn><div className="flex items-center gap-4"><span className="flex size-16 items-center justify-center rounded-[22px] text-xl font-black text-white shadow-[0_5px_16px_rgba(52,211,153,.25)]" style={{background:currentProfile.avatarGradient}}>{currentProfile.initial}</span><div><p className="text-xs text-[color:var(--muted-foreground)]">Power Up 2 学习者</p><h1 className="text-[24px] font-extrabold">{currentProfile.nickname}的学习空间</h1></div></div></FadeIn></header>
  <main className="space-y-5 px-5"><FadeIn><Card className="rounded-[24px] border-0 bg-[color:var(--mint-soft)] p-5 shadow-none"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-[color:var(--primary-deep)]">本周共学习</p><p className="mt-1 text-[32px] font-black">42 <span className="text-sm font-semibold">分钟</span></p></div><div className="flex size-14 items-center justify-center rounded-[20px] bg-white/80 text-[color:var(--primary-deep)]"><BarChart3 className="size-6" /></div></div><div className="mt-4"><div className="mb-2 flex justify-between text-xs"><span>本周目标 60 分钟</span><span className="font-bold">70%</span></div><Progress value={70} className="h-2 bg-white [&>div]:bg-[color:var(--primary)]" /></div></Card></FadeIn>
  <Stagger className="grid grid-cols-3 gap-2" stagger={.08}>{[{icon:Clock3,v:"12",l:"今日分钟",c:"var(--blue-soft)",fg:"var(--blue-deep)"},{icon:Search,v:"7",l:"查过新词",c:"#FFF7DF",fg:"#B7791F"},{icon:BookOpenCheck,v:"3",l:"完成复习",c:"var(--mint-soft)",fg:"var(--primary-deep)"}].map(x => <motion.div variants={fadeUp} key={x.l}><Card className="rounded-[20px] border-0 p-3 text-center shadow-[0_2px_10px_rgba(45,59,54,.05)]"><div className="mx-auto flex size-9 items-center justify-center rounded-xl" style={{background:x.c,color:x.fg}}><x.icon className="size-4" /></div><p className="mt-2 text-xl font-black">{x.v}</p><p className="text-[10px] text-[color:var(--muted-foreground)]">{x.l}</p></Card></motion.div>)}</Stagger>
  <section><h2 className="mb-3 text-[17px] font-extrabold">学习概览</h2><div className="overflow-hidden rounded-[22px] bg-white shadow-[0_2px_12px_rgba(45,59,54,.05)]"><MenuRow icon={CalendarDays} label="本周学习日" value="4 天"/><MenuRow icon={BookOpenCheck} label="学习中词汇" value="3 个"/><MenuRow icon={ShieldCheck} label="护眼时长" value="12 / 40 分钟" last/></div></section>
  <section><h2 className="mb-3 text-[17px] font-extrabold">家庭设置</h2><div className="overflow-hidden rounded-[22px] bg-white shadow-[0_2px_12px_rgba(45,59,54,.05)]"><MenuRow icon={Users} label="切换学习者" value="小宇"/><MenuRow icon={Settings2} label="学习偏好" value="双语字幕"/><Button variant="ghost" onClick={() => nav("/parent")} className="flex h-16 w-full items-center justify-start gap-3 rounded-none px-4 text-left hover:bg-[color:var(--surface-soft)]"><span className="flex size-10 items-center justify-center rounded-xl bg-[color:var(--blue-soft)] text-[color:var(--blue-deep)]"><LockKeyhole className="size-5" /></span><span className="flex-1 text-sm font-bold">家长控制台</span><span className="text-xs font-normal text-[color:var(--muted-foreground)]">需要 PIN</span><ChevronRight className="size-4 text-[color:var(--muted-foreground)]" /></Button></div></section>
  </main></div>; }
function MenuRow({icon:Icon,label,value,last=false}:{icon:typeof Clock3;label:string;value:string;last?:boolean}) { return <div className={`flex min-h-16 items-center gap-3 px-4 ${last?"":"border-b border-[color:var(--border)]"}`}><span className="flex size-10 items-center justify-center rounded-xl bg-[color:var(--surface-soft)] text-[color:var(--primary-deep)]"><Icon className="size-5" /></span><span className="flex-1 text-sm font-semibold">{label}</span><span className="text-xs text-[color:var(--muted-foreground)]">{value}</span><ChevronRight className="size-4 text-[color:var(--muted-foreground)]" /></div>; }
