import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Volume2, RotateCcw, PlayCircle, ChevronLeft, ChevronRight, Layers3, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { vocabularyItems, type VocabStatus } from "@/data/mock";
import { FadeIn } from "@/components/MotionPrimitives";
import { toast } from "sonner";

const tabs: { key: VocabStatus; label: string }[] = [{ key: "learning", label: "学习中" }, { key: "review", label: "待复习" }, { key: "mastered", label: "已掌握" }];
export default function VocabularyPage() {
  const [tab, setTab] = useState<VocabStatus>("learning"); const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false);
  const list = useMemo(() => vocabularyItems.filter(v => v.status === tab), [tab]); const item = list[index % Math.max(1, list.length)];
  const switchTab = (key: VocabStatus) => { setTab(key); setIndex(0); setFlipped(false); };
  const score = (label: string, next: string) => { toast.success(`${item.lemma} · ${label}`, { description: `下次复习：${next}` }); setFlipped(false); setIndex((index + 1) % list.length); };
  return <div className="flex min-h-full flex-col bg-[color:var(--background)] px-5 pb-5 pt-3">
    <FadeIn><div className="flex items-end justify-between"><div><p className="text-xs font-bold text-[color:var(--primary-deep)]">记住真实表达</p><h1 className="text-[24px] font-extrabold">我的生词本</h1></div><div className="flex h-10 items-center gap-1.5 rounded-xl bg-[color:var(--mint-soft)] px-3 text-xs font-bold text-[color:var(--primary-deep)]"><Layers3 className="size-4" />{vocabularyItems.length} 词</div></div>
      <div className="mt-4 grid grid-cols-3 rounded-2xl bg-white p-1 shadow-[0_2px_10px_rgba(45,59,54,.05)]">{tabs.map(t => <Button key={t.key} variant="ghost" onClick={() => switchTab(t.key)} className={`h-11 rounded-xl text-xs ${tab === t.key ? "bg-[color:var(--mint-soft)] font-bold text-[color:var(--primary-deep)]" : "text-[color:var(--muted-foreground)]"}`}>{t.label}<span className="ml-1">{vocabularyItems.filter(v => v.status === t.key).length}</span></Button>)}</div></FadeIn>

    {item ? <div className="flex flex-1 flex-col justify-center py-5"><div className="mb-3 flex items-center justify-between px-2 text-xs text-[color:var(--muted-foreground)]"><Button size="icon" variant="ghost" onClick={() => { setIndex((index - 1 + list.length) % list.length); setFlipped(false); }} className="size-11 rounded-full"><ChevronLeft className="size-5" /></Button><span>{index + 1} / {list.length} · 点击卡片翻面</span><Button size="icon" variant="ghost" onClick={() => { setIndex((index + 1) % list.length); setFlipped(false); }} className="size-11 rounded-full"><ChevronRight className="size-5" /></Button></div>
      <div className="relative mx-auto h-[340px] w-full [perspective:1200px]" onClick={() => setFlipped(!flipped)}><motion.div className="relative size-full cursor-pointer [transform-style:preserve-3d]" animate={{ rotateY: flipped ? 180 : 0 }} transition={{ type: "spring", damping: 24, stiffness: 220 }}>
        <FlashCardFace front item={item} /><FlashCardFace item={item} />
      </motion.div></div>
      <AnimatePresence mode="wait">{flipped ? <motion.div key="score" initial={{ opacity:0,y:8 }} animate={{ opacity:1,y:0 }} exit={{ opacity:0 }} className="mt-4 grid grid-cols-3 gap-2"><ScoreButton label="忘了" color="var(--danger)" bg="var(--danger-soft)" onClick={() => score("忘了", "10 分钟后")} /><ScoreButton label="模糊" color="#B7791F" bg="#FFF7DF" onClick={() => score("模糊", "明天")} /><ScoreButton label="记得" color="var(--primary-deep)" bg="var(--mint-soft)" onClick={() => score("记得", "3 天后")} /></motion.div> : <motion.p key="hint" initial={{opacity:0}} animate={{opacity:1}} className="mt-4 text-center text-xs text-[color:var(--muted-foreground)]">先在心里想一想，再翻面看答案</motion.p>}</AnimatePresence></div> : <div className="flex flex-1 flex-col items-center justify-center text-center"><Check className="mb-3 size-12 text-[color:var(--primary)]" /><h2 className="font-bold">这里暂时没有单词</h2><p className="mt-1 text-sm text-[color:var(--muted-foreground)]">去视频里点一点新词吧</p></div>}
  </div>;
}

function FlashCardFace({ item, front = false }: { item: (typeof vocabularyItems)[number]; front?: boolean }) { return <div className={`absolute inset-0 flex flex-col rounded-[28px] border border-[color:var(--border)] bg-white p-6 shadow-[0_10px_36px_rgba(45,59,54,.10)] [backface-visibility:hidden] ${front ? "" : "[transform:rotateY(180deg)]"}`}>{front ? <><div className="flex justify-between"><span className="rounded-full bg-[color:var(--blue-soft)] px-3 py-1.5 text-xs font-bold text-[color:var(--blue-deep)]">{item.pos} · {item.phonetic}</span><Button size="icon" variant="ghost" className="size-12 rounded-full bg-[color:var(--mint-soft)] text-[color:var(--primary-deep)]"><Volume2 className="size-5" /></Button></div><div className="flex flex-1 flex-col items-center justify-center"><h2 className="text-[36px] font-black tracking-tight">{item.surface}</h2><p className="mt-2 text-sm text-[color:var(--muted-foreground)]">听发音，想一想它的意思</p></div><div className="rounded-2xl bg-[color:var(--surface-soft)] p-4"><p className="text-[17px] font-semibold leading-7">{item.sentenceEn}</p><p className="mt-2 flex items-center gap-1.5 text-xs text-[color:var(--muted-foreground)]"><Volume2 className="size-3.5" />来自原句 · {item.timestampLabel}</p></div></> : <><div className="flex items-center justify-between"><span className="text-xs font-bold text-[color:var(--primary-deep)]">答案</span><RotateCcw className="size-4 text-[color:var(--muted-foreground)]" /></div><div className="mt-4 rounded-2xl bg-[color:var(--mint-soft)] p-4"><h2 className="text-[21px] font-extrabold">{item.meaningZh}</h2><p className="mt-1 text-xs text-[color:var(--primary-deep)]">{item.phonetic} · {item.pos}</p></div><div className="mt-4"><p className="text-[16px] font-semibold leading-7">{item.sentenceEn.replace("___", item.surface)}</p><p className="mt-1 text-sm leading-6 text-[color:var(--muted-foreground)]">{item.sentenceZh}</p></div><Button variant="outline" className="mt-auto h-12 rounded-2xl border-[color:var(--border)] text-[color:var(--blue-deep)]"><PlayCircle className="mr-2 size-5" />回到 {item.timestampLabel} 看原句</Button></>}</div>; }
function ScoreButton({ label,color,bg,onClick }: { label:string;color:string;bg:string;onClick:()=>void }) { return <Button variant="ghost" onClick={e => { e.stopPropagation(); onClick(); }} className="h-14 rounded-2xl text-sm font-bold" style={{ color, background:bg }}>{label}</Button>; }
