package com.lazyeng.family.core.model

@JvmInline value class FamilyId(val value: String)
@JvmInline value class ProfileId(val value: String)
@JvmInline value class VideoId(val value: String)
@JvmInline value class VideoAssetId(val value: String)
@JvmInline value class SubtitleTrackId(val value: String)
@JvmInline value class SubtitleVersionId(val value: String)
@JvmInline value class SubtitleLineId(val value: String)
@JvmInline value class LookupEventId(val value: String)
@JvmInline value class ReviewAttemptId(val value: String)
@JvmInline value class GeneratedContentId(val value: String)
@JvmInline value class AiJobId(val value: String)
@JvmInline value class LearningSessionId(val value: String)
@JvmInline value class EventUuid(val value: String)
@JvmInline value class CacheKey(val value: String)
@JvmInline value class FileReference(val value: String)
@JvmInline value class SecretReference(val value: String)
@JvmInline value class TranslationVersionId(val value: String)
